# This workflow will build a MuleSoft project and deploy to the CloudHub PROD enviornment
 
name: Build, Test and Deploy to PROD
 
# Triggers the workflow on push for the develop branch only
on:
 # Triggers the workflow manually only for PROD deployments
  workflow_dispatch:
  # Required user inputs when triggering the workflow
    inputs:
      workerSize:
        description: 'Size of Mule Worker'     
        required: true
        default: 'MICRO'
      numberOfWorkers:
        description: 'Number of Mule Workers'     
        required: true
        default: '1'

jobs:
  # Build, test and deplloy the Mule artifact using remote workflows
  workflow:
    uses: esocrm/bmw-esocrm-mule-workflows/.github/workflows/prod_workflow.yml@master
    secrets: inherit
