# This is a reusable workflow that deploys the project to DEV environment

name: Deploy the Project to DEV environment

# Trigger when being called by another workflow
on:
  workflow_call:
    inputs:
      workerType: 
        required: false
        type: string
        default: "MICRO"
      workerCount:
        required: false
        type: string
        default: '1'

jobs:
  # Bulid and test the project
  build-and-deploy:
    # Represents a sequence of tasks to be performed in this job
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so that the job can access it
      - uses: actions/checkout@v3

      # Installs Java JDK v11
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"

      # Installs Maven v3.6.3
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3

      # Builds and tests the mule artifact using Maven
      - name: Build and Test
        run: |
          mvn -B package --file pom.xml

      # Read artifactId from POM file and save into a variable
      - name: Get Artifact Name
        run: echo "ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      # Deploy to Cloudhub DEV Environment
      - name: Deploy to DEV
        env:
          ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}
          CONNECTED_CLIENT_ID: ${{ secrets.MULETALKS_DEPLOYER_PREPROD_CLIENT_ID }}
          CONNECTED_CLIENT_SECRET: ${{ secrets.MULETALKS_DEPLOYER_PREPROD_CLIEN_SECRET }}
          MULE_ENV: dev
          ANYPOINT_ENV: DEV
          WORKER_TYPE: ${{ github.event.inputs.workerType }}
          NUMBER_OF_WORKERS: ${{ github.event.inputs.workerCount }}
          REGION: eu-central-1
          BUSINESS_GROUP: mboss37\muletalks
          ANYPOINT_PLATFORM_URI: https://anypoint.mulesoft.com
          ANYPOINT_ANALYTICS_URI: https://analytics-ingest.anypoint.mulesoft.com
          ANYPOINT_PLATFORM_CLIENT_ID: ${{ secrets.MULETALKS_ANYPOINT_PLATFORM_CLIENT_ID }}
          ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.MULETALKS_ANYPOINT_PLATFORM_CLIENT_SECRET }}
        run: |
          mvn deploy -DmuleDeploy \
          -Dapplication.name="$ARTIFACT_NAME-v1-dev" \
          -Danypoint.platform.muletalks.connectedapp.client_id=$CONNECTED_CLIENT_ID \
          -Danypoint.platform.muletalks.connectedapp.client_secret=$CONNECTED_CLIENT_SECRET \
          -Dmule.env=$MULE_ENV \
          -Danypoint.muletalks.env=$ANYPOINT_ENV \
          -Danypoint.muletalks.workertype=$WORKER_TYPE \
          -Danypoint.muletalks.numberofworkers=$NUMBER_OF_WORKERS \
          -Danypoint.muletalks.region=$REGION \
          -Danypoint.muletalks.bg=$BUSINESS_GROUP \
          -Danypoint.platform.analytics_base_uri=$ANYPOINT_ANALYTICS_URI \
          -Danypoint.platform.base_uri=$ANYPOINT_PLATFORM_URI \
          -Danypoint.platform.muletalks.client_secret=$ANYPOINT_PLATFORM_CLIENT_SECRET \
          -Danypoint.platform.muletalks.client_id=$ANYPOINT_PLATFORM_CLIENT_ID \
          -DskipTests=true
